django_user_mgmt/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views

urlpatterns = [
    # path('admin/', admin.site.urls),

    # 部门管理
    path('depart_list/', views.depart_list),
    path('depart_add/', views.depart_add),
    path('depart_delete/', views.depart_delete),
    path('depart/<int:nid>/edit/', views.depart_edit),

    # 用户管理
    path('user_list/', views.user_list),
    path('user_add/', views.user_add),

    # path('user_add/form/', views.user_add_form),  form的实现当时
    path('user_add/modelform/', views.user_add_modelform),
    path('user/<int:nid>/edit/', views.user_edit),
    path('user/<int:nid>/delete/', views.user_delete),

    # 靓号管理
    path('phone_list/', views.phone_list),
    path('phone_add/', views.pretty_add_modelform),
    # path('phone/<int:nid>/edit/', views.phone_edit),
]

app01/models.py
from django.db import models


# Create your models here.

class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='部门名称', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name='姓名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    accont = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name='入职时间')  # 时间格式是：年 月 日    时：分
    create_time = models.DateField(verbose_name='入职时间')  # 时间格式是：年 月 日

    # 外键约束
    #   to= 后面跟的是需要外键连接的表
    #   to_field= 后面跟的是外键链接的值
    # 当部门表中的值被删除，员工表会有两种表现
    #   1. on_delete=models.CASCADE 级联删除
    #   2. on_delete=models.SET_NULL 将值置为空

    depart = models.ForeignKey(verbose_name='部门',to='Department', to_field='id', on_delete=models.CASCADE)
    # depart = models.ForeignKey(to='Department', to_field='id',
    #                            null=True,
    #                            blank=True,
    #                            on_delete=models.SET_NULL,
    #                            )

    # django特有的约束，在数据库表的记录中，对这个gender字段可以记录的值为1或者2，而1和2所表示的意思是在gender_choices
    # 中规定的
    gender_choices = (
        (1,'男'),
        (2,'女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别',choices=gender_choices)


class PrettyNum(models.Model):
    """靓号管理"""
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    price = models.IntegerField(verbose_name='价格')
    status_choices=(
        (1, '已占用'),
        (2, '未占用'),
    )
    level_choices = (
        (1, '1级'),
        (2, '2级'),
        (3, '3级'),
        (4, '4级'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices,default=2)
    level = models.SmallIntegerField(verbose_name='级别', choices=level_choices,default=1)

app01/views.py
import re

from django.shortcuts import render,redirect,HttpResponse
from app01.models import *

# Create your views here.

def depart_list(request):
    """部门列表"""
    department_list = Department.objects.all()
    return render(request,'depart_list.html',
                  {'dpt_list': department_list}
                  )


def depart_add(request):
    """部门增加"""
    if request.method == 'GET':
        return render(request,'depart_add.html')

    depart = request.POST.get('depart')
    Department.objects.create(title=depart)
    return redirect('/depart_list/')


def depart_delete(request):
    """部门删除"""
    nid = request.GET.get('nid')
    Department.objects.filter(id=nid).delete()
    return redirect('/depart_list/')


def depart_edit(request,nid):
    """部门修改"""
    if request.method == 'GET':
        query_data = Department.objects.filter(id=nid).first()
        row_data = query_data.title
        return render(request,'depart_edit.html',
                      {'title':row_data}
                      )

    new_depart = request.POST.get('depart')
    Department.objects.filter(id=nid).update(title=new_depart)
    return redirect('/depart_list/')


def user_list(request):
    """用户列表"""
    if request.method == 'GET':
        queryset = UserInfo.objects.all()
        # print(queryset)
        # print(dir(queryset))
        """
        for item in  queryset:
            print(item.name,item.password,
                  # 数据库中保存的时间类型为datatime类型，要将datatime类型格式化为字符串就需要.strftime方法
                  item.create_time.strftime("%Y-%m-%d"),
                  # 通过get_gender_display()方法直接可以获取choices数字所对应的值
                  item.get_gender_display(),
                  # 通过.depart（数据库中定义的字段），可以直接获得所关联的外键数据库表的记录
                  item.depart.title)
        """
        return render(request, 'user_list.html',
                      {'queryset':queryset}
                      )


def user_add(request):
    """用户添加 传统方法"""
    if request.method == 'GET':
        to_web_dict = {
            'gender':UserInfo.gender_choices,
            'depart':Department.objects.all()
        }
        print(Department.objects.all().values())
        return render(request,'user_add.html',to_web_dict)

    name = request.POST.get('name')
    pwd = request.POST.get('pwd')
    age = request.POST.get('age')
    ac = request.POST.get('ac')
    ctime = request.POST.get('ctime')
    gender = request.POST.get('gender')
    depart = request.POST.get('depart')

    UserInfo.objects.create(name=name,password=pwd,age=age,accont=ac,
                            create_time=ctime,gender=gender,depart_id=depart)
    return redirect('/user_list/')

"""
form的实现方式
from django import forms
class UserForm(forms.Form):
    user = forms.CharField(widget=forms.TextInput)
    pwd = forms.CharField(widget=forms.PasswordInput)
    ctime = forms.CharField(widget=forms.DateInput)


def user_add_form(request):
    form = UserForm
    return render(request,'user_add_form.html',{'form':form})
"""

from django import forms

class UserModelForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput,min_length=3)
    name = forms.CharField(min_length=2,label="姓名")

    class Meta:
        model = UserInfo
        fields = ['name','password','age','accont','create_time','gender','depart']
        widgets = {
            # 'name': forms.TextInput(attrs={'class':'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),   # 修改password字段的input标签类型为PasswordInput，并添加CSS样式
            # 'age': forms.TextInput(attrs={'class':'form-control'}),
            # 'create_time': forms.DateInput(attrs={'class':'form-control'}),
            # 'gender': forms.TypedChoiceField(attrs={'class':'form-control'}),
            # 'depart': forms.ModelChoiceField(attrs={'class':'form-control'})
        }

    # 给ModelForm生成的input标签添加CSS样式
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name,field in self.fields.items():
            # print(name,field)
            field.widget.attrs = {'class':'form-control','placeholder':field.label}


def user_add_modelform(request):
    if request.method == 'GET':
        form = UserModelForm()
        print('form的内容',form)
        return render(request,'user_add_modelform.html',{'form':form})

    # 用户POST提交数据，数据校验
    form = UserModelForm(data=request.POST)

    if form.is_valid():
        print(form.cleaned_data)
        # 将数据保存至数据库
        form.save()
        return redirect('/user_list/')
    else:
        return render(request, 'user_add_modelform.html', {'form': form})


def user_edit(request,nid):
    """编辑用户"""
    # print(nid)
    if request.method == "GET":
        row_data = UserInfo.objects.filter(id=nid).first()
        form = UserModelForm(instance=row_data)

        return render(request,'user_edit.html',{'form':form})


    row_data = UserInfo.objects.filter(id=nid).first()
    dir(row_data)
    form = UserModelForm(data=request.POST,instance=row_data)
    if form.is_valid():
        # 将数据保存至数据库
        form.save()
        return redirect('/user_list/')
    else:
        return render(request, 'user_add_modelform.html', {'form': form})


def user_delete(request,nid):
    """用户删除"""
    UserInfo.objects.filter(id=nid).delete()
    return redirect('/user_list/')


def phone_list(request):
    """靓号列表"""
    if request.method == "GET":
        form = PrettyNum.objects.all()
        return render(request,'phone_list.html',{"forms":form})





class PrettyModelForm(forms.ModelForm):
    """靓号通过ModelForm方式添加的类"""
    # 方式一：验证手机号码 通过在ModelForm的类中自己定义字段的正则表达式
    from django.core.validators import RegexValidator
    mobile = forms.CharField(
        label="手机号",
        validators=[RegexValidator(r'^1[3-9]\d{9}$','手机号格式错误')],
    )

    class Meta:
        model = PrettyNum
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name,field in self.fields.items():
            # print(name,field)
            field.widget.attrs = {'class':'form-control','placeholder':field.label}

    # 方式二：通过钩子方法
    # def clean_mobile(self):
    #     from django.core.exceptions import ValidationError
    #     txt_mobile = self.cleaned_data["mobile"]
    #     re_mobile = re.match(r'^1[3-9]\d{9}$',txt_mobile)
    #     # 验证通过返回用户输入的数据
    #     if re_mobile:
    #         return txt_mobile
    #     # 验证不通过则返回报错信息
    #     else:
    #         raise ValidationError("格式错误")

def pretty_add_modelform(request):
    """靓号添加"""
    if request.method == "GET":
        form = PrettyModelForm()
        return render(request,"pretty_add_modelform.html",{"forms":form})

    # 用户POST提交数据，数据校验
    form = PrettyModelForm(data=request.POST)

    if form.is_valid():
        # print(form.cleaned_data)
        # 将数据保存至数据库
        form.save()
        return redirect('/phone_list/')
    else:
        return render(request, 'pretty_add_modelform.html', {'forms': form})

app01/templates/depart_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="/depart_add/">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">新建部门</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" name="depart"
                               placeholder="部门名称">
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/depart_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <form method="post" >
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">张庆青每天都对我很凶</label>
                <input type="text" class="form-control" id="exampleInputEmail1"  name="depart" value="{{ title }}">
            </div>

            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
{% endblock %}

app01/templates/depart_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/depart_add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建部门</a>
        </div>


        <div style="border: gray solid 1px;background-color: #888888;font-size: larger;">

            <div style="color: white;padding: 5px;">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>   部门列表
            </div>
        </div>
        <div class="bs-example" data-example-id="bordered-table">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>部门名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                    {% for obj in dpt_list %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.title }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/depart/{{ obj.id }}/edit">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/depart_delete/?nid={{ obj.id }}">删除</a>
                        </td>
                    </tr>
                   {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

{% endblock %}

app01/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static '/plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">

    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">员工管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/depart_list/">部门管理 <span class="sr-only">(current)</span></a></li>
                <li ><a href="/user_list/">员工管理 <span class="sr-only">(current)</span></a></li>
                <li ><a href="/phone_list/">靓号管理 <span class="sr-only">(current)</span></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link222</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div>
    {% block content %} {% endblock %}
</div>


<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

app01/templates/phone_list.html
{% extends "layout.html" %}


{% block content %}
    <div class="container">

        <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="#">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新增号码</a>
            <!-- form的实现方式
            <a class="btn btn-success" href="/user_add/form/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建员工Form</a>
            -->

            <a class="btn btn-success" href="/phone_add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新增号码ModelForm</a>


        </div>


        <div style="border: gray solid 1px;background-color: #888888;font-size: larger;">
            <div style="color: white;padding: 5px;">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>   靓号列表
            </div>
        </div>
        <div class="bs-example" data-example-id="bordered-table">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>号码</th>
                    <th>价格</th>
                    <th>状态</th>
                    <th>级别</th>
                </tr>
                </thead>
                <tbody>
                    {% for obj in forms %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display}}</td>
                        <td>{{ obj.get_level_display}}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/phone/{{ obj.id}}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="#">删除</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

    </div>


{% endblock %}

app01/templates/pretty_add_modelform.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新增号码</h3>
            </div>
            <div class="panel-body">
                <form method="post"  novalidate>
                    {% csrf_token %}
                    {% for field in forms %}
                    <div class="form-group">

                        <label >{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors.0 }}</span>

                    </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/pretty_edit.html
{% extends "layout.html" %}


{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">编辑号码</h3>
            </div>
            <div class="panel-body">
                <form method="post"  novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">

                        <label >{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors.0 }}</span>

                    </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/user_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新增员工</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="/user_add/">
                    {% csrf_token %}
                    <div class="form-group">

                        <label for="exampleInputEmail1">姓名</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" name="name"
                               placeholder="姓名">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">密码</label>
                        <input type="password" class="form-control" id="exampleInputEmail1" name="pwd"
                               placeholder="密码">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">年龄</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" name="age"
                               placeholder="年龄">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">账户</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" name="ac"
                               placeholder="账户">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">创建时间</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" name="ctime"
                               placeholder="创建时间">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">性别</label>
                        <select class="form-control" name="gender" id="">
                            {% for obj in gender %}
                                <option value="{{ obj.0 }}">{{ obj.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">部门</label>
                        <select class="form-control" name="depart" id="">
                            {% for obj in depart %}
                                <option value="{{ obj.id }}">{{ obj.title }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/user_add_form.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新增员工</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="/user_add/">
                    {% csrf_token %}
                    <div class="form-group">

                        <span>用户名</span>{{ form.user }}
                        <span>密码</span>{{ form.pwd }}
                        <span>创建时间</span>{{ form.ctime }}
                    </div>


                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/user_add_modelform.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新增员工</h3>
            </div>
            <div class="panel-body">
                <form method="post"  novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">

                        <label >{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors.0 }}</span>

                    </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/user_edit.html
{% extends "layout.html" %}


{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新增员工</h3>
            </div>
            <div class="panel-body">
                <form method="post"  novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">

                        <label >{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors.0 }}</span>

                    </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/user_add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建员工</a>
            <!-- form的实现方式
            <a class="btn btn-success" href="/user_add/form/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建员工Form</a>
            -->

            <a class="btn btn-success" href="/user_add/modelform/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建员工ModelForm</a>


        </div>


        <div style="border: gray solid 1px;background-color: #888888;font-size: larger;">
            <div style="color: white;padding: 5px;">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>   员工列表
            </div>
        </div>
        <div class="bs-example" data-example-id="bordered-table">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>账户</th>
                    <th>创建时间</th>
                    <th>性别</th>
                    <th>部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                    {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.accont }}</td>
                        <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                        <td>{{ obj.get_gender_display}}</td>
                        <td>{{ obj.depart.title}}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

{% endblock %}